#define CONFIG_MSIZE 0x8000000
#define CONFIG_MBASE 0x80000000
#define RESET_VECTOR CONFIG_MBASE

#define CONFIG_RT_CHECK 1
#define LLVM_VERSION_MAJOR 18

#define CONFIG_ISA_riscv 1
#define CONFIG_RVE 1

#define CONFIG_TRACE 1
#define CONFIG_MTRACE 1
#define CONFIG_ITRACE 1
#define CONFIG_FTRACE 1
#define CONFIG_DIFFTEST 1

#define CONFIG_DEBUG_PRINT_INFO 1

#define CONFIG_DEBUG_PMEM 1
