#define CONFIG_MSIZE 0x8000000
#define CONFIG_MBASE 0x80000000
#define RESET_VECTOR CONFIG_MBASE

#define CONFIG_RT_CHECK 1
#define LLVM_VERSION_MAJOR 18

#define CONFIG_ISA_riscv 1
#define CONFIG_RVE 2

// #define CONFIG_TRACE 1

// #define CONFIG_DEBUG_PRINT_INFO 1

#ifdef CONFIG_TRACE

#define CONFIG_MTRACE 1
#ifdef CONFIG_MTRACE
#define CONFIG_DEBUG_PMEM 1
// #define CONFIG_LOG_EVERY_MTRACE 1
#endif

#define CONFIG_ITRACE 1
#ifdef CONFIG_ITRACE
#define CONFIG_LOG_EVERY_ITRACE 1
#endif

#define CONFIG_FTRACE 1
#ifdef CONFIG_FTRACE
#define CONFIG_DEBUF_J_inst 1
#define CONFIG_PRINT_FUNC_JMP 1
#endif

#endif

// #define CONFIG_DIFFTEST 1

// #define CONFIG_FST 1

// device setting
/* vga */
#define CONFIG_HAS_VGA 1
#ifdef CONFIG_HAS_VGA

// #define CONFIG_VGA_SIZE_800x600
#ifndef CONFIG_VGA_SIZE_800x600
#define CONFIG_VGA_SIZE_400x300 1
#endif

#define CONFIG_VGA_SHOW_SCREEN 1

#endif
